// Converts a theme.json into a tokens.css file containing CSS custom properties.
// Naming convention: --vdx-<group>-<subgroup>-<key>, all in kebab-case.
//
// CLI:
//   node lib/token-to-css.js                  # rebuild every registered theme
//   node lib/token-to-css.js themes/<id>      # rebuild a single theme

import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { loadTheme } from "./theme-loader.js";
import { listThemes, DEFAULT_THEMES_DIR } from "./theme-registry.js";

// Top-level theme fields that are scalar metadata, not token groups. Anything
// else under the theme root is treated as a flatten-able token tree. Driving
// the group set off the data (rather than a hard-coded list) means a future
// schema addition like `colors` → `motion` → `effects` is reflected in the
// generated tokens.css automatically.
const SCALAR_FIELDS = new Set(["id", "name", "version", "description", "defaultLang"]);

function camelToKebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

// Reject any value that could break out of a CSS declaration. A token value
// must be a single declaration value: no semicolons, no braces, no angle
// brackets, no newlines.
const CSS_SAFE_VALUE = /^[^;{}<>\n\r]+$/;

function flatten(obj, prefix, out) {
  for (const [k, v] of Object.entries(obj)) {
    const key = camelToKebab(String(k));
    const path = prefix ? `${prefix}-${key}` : key;
    if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      flatten(v, path, out);
    } else {
      const value = String(v);
      if (!CSS_SAFE_VALUE.test(value)) {
        throw new Error(
          `Unsafe token value at '${path}': ${JSON.stringify(value)} contains characters that could break out of a CSS declaration (one of ; { } < > or newline).`,
        );
      }
      out[path] = value;
    }
  }
}

// Numeric-aware key compare. Splits each key into runs of digits vs non-digits
// and compares chunk-by-chunk. Pure JS — no ICU dependence, no integer
// overflow — so output is byte-identical across Node builds and operating
// systems. Without this, `localeCompare` would put `spacing-10` before
// `spacing-2` and risk drifting across `--icu-data-dir` configurations, which
// would break the byte-equality test in samsung-theme.test.js.
//
// Numeric chunks are compared by stripped magnitude (length-then-lex on the
// no-leading-zero form) so very long digit runs that exceed
// Number.MAX_SAFE_INTEGER still order correctly. Ties on magnitude fall back
// to the raw chunk so "09" and "9" stay distinct and stably ordered.
export function compareKeys(a, b) {
  const A = a.match(/\d+|\D+/g) || [];
  const B = b.match(/\d+|\D+/g) || [];
  const n = Math.min(A.length, B.length);
  for (let i = 0; i < n; i++) {
    const aChunk = A[i];
    const bChunk = B[i];
    const aNum = /^\d+$/.test(aChunk);
    const bNum = /^\d+$/.test(bChunk);
    if (aNum && bNum) {
      const aStripped = aChunk.replace(/^0+(?=\d)/, "");
      const bStripped = bChunk.replace(/^0+(?=\d)/, "");
      if (aStripped.length !== bStripped.length) {
        return aStripped.length - bStripped.length;
      }
      if (aStripped !== bStripped) {
        return aStripped < bStripped ? -1 : 1;
      }
      if (aChunk !== bChunk) return aChunk < bChunk ? -1 : 1;
    } else if (aChunk !== bChunk) {
      return aChunk < bChunk ? -1 : 1;
    }
  }
  return A.length - B.length;
}

export function themeToCss(theme) {
  const flat = {};
  // Derive the group list from the theme itself. Scalar metadata is excluded;
  // anything else that's a plain object is a token tree. The final output is
  // sorted by full flat key via compareKeys below, so the iteration order here
  // doesn't affect the result — we just need every group to be visited.
  for (const k of Object.keys(theme)) {
    if (SCALAR_FIELDS.has(k)) continue;
    const v = theme[k];
    if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      // Kebab-case the group name too. All existing groups are lowercase
      // (colors, typography, spacing, …) so this is a no-op for them, but
      // future camelCase groups like `zIndex` need to flatten to `z-index`.
      flatten(v, camelToKebab(k), flat);
    }
  }

  const lines = [
    "/* Generated by lib/token-to-css.js — do not edit by hand. */",
    `/* Theme: ${theme.id} (${theme.name}) v${theme.version} */`,
    ":root {",
  ];
  for (const [key, value] of Object.entries(flat).sort(([a], [b]) => compareKeys(a, b))) {
    lines.push(`  --vdx-${key}: ${value};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function buildTokensCss(themeDir) {
  const theme = loadTheme(themeDir);
  const css = themeToCss(theme);
  const outPath = join(themeDir, "tokens.css");
  writeFileSync(outPath, css);
  return outPath;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const themeDir = process.argv[2];
  if (themeDir) {
    // Single-theme branch takes a user-supplied path; resolve from cwd.
    const out = buildTokensCss(resolve(themeDir));
    console.log(`Wrote ${out}`);
  } else {
    // No-arg branch rebuilds every registered theme. We must NOT use cwd:
    // resolving from the registry's DEFAULT_THEMES_DIR keeps this working
    // regardless of where the user invokes node from.
    const ids = listThemes();
    if (ids.length === 0) {
      console.error("No themes registered.");
      process.exit(1);
    }
    for (const id of ids) {
      const out = buildTokensCss(join(DEFAULT_THEMES_DIR, id));
      console.log(`Wrote ${out}`);
    }
  }
}
